[project]
name = "langchain-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-identity>=1.20.0",
    "langchain>=0.3.20",
    "langchain-openai>=0.3.8",
]
